[package]
name = "cactus-plugin-keychain-memory-wasm"
version = "2.0.0-rc.4"
description = "A demonstrator plugin for the Cacti blockchain & DLT interoperability project. Do NOT use in production!"
license = "Apache-2.0"
repository = "https://github.com/hyperledger/cacti"
authors = ["Peter Somogyvari <peter.somogyvari@accenture.com>"]
edition = "2018"

[build]
target-dir = "../../../../dist/target-rustc/"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.42"
serde-wasm-bindgen = "0.6.5"

getrandom = { version = "0.2", features = ["js"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

js-sys = "0.3.69"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
wasm-bindgen-test = "0.3.42"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
