[Database]
URL = "postgres://chainlink_user:3kcixh_xgm3_yJs_uV9q@postgres1:5432/chainlink_db?sslmode=disable" # Example
AllowSimplePasswords = true # Default

[Password]
Keystore = '3kcixh_xgm3_yJs_uV9q' # Required
